cart/urls.py
from django.urls import path, include
from . import views

app_name = 'cart' # обязательное условие иначе не найдет!

urlpatterns = [
    path('add-to-cart', views.add_to_cart, name='add_to_cart'), # для AJAX в main/custom.js файле
    path('delete-from-cart', views.delete_cart_item, name='delete_from_cart'), # для AJAX в main/custom.js файле
    path('update-cart', views.update_cart_item, name='update_cart_item'), # для AJAX в main/custom.js файле
    path('orders/', views.cart_list, name='cart_list'),
]

shop/urls.py
from django.contrib import admin
from django.urls import path
from main import views
from django.conf.urls.static import static
from django.urls import include
from django.conf import settings

urlpatterns = [
    # Приложение Jet-Admin (видоизмененная админка)
    path('jet/', include('jet.urls')),
    path('jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),
    path('admin/', admin.site.urls),

    path('', views.home, name='home'),

    # Приложение Cart
    path('cart/', include('cart.urls', namespace='cart')),

    # Приложение Users
    path('users/', include('users.urls', namespace='users')),
    
    path('category_list/', views.category_list, name='category_list'),
    path('brand_list/', views.brand_list, name='brand_list'),
    path('product_list/', views.product_list, name='product_list'),
    path('category_product_list/<int:cat_id>', views.category_product_list, name='category_product_list'),
    path('brand_product_list/<int:brand_id>', views.brand_product_list, name='brand_product_list'),
    path('product/<str:slug>/<int:id>', views.product_detail, name='product_detail'),
    path('search/', views.search, name='search'),
    path('filter-data/', views.filter_data, name='filter_data'),
    path('load-more-data/', views.load_more_data, name='load_more_data'),

    # Тестирование
    path('test/', views.test, name='test'),
    # path('gallery/', views.gallery, name='gallery'),
    path('slider/', views.slider, name='slider'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path, include
from . import views

app_name = 'users' # обязательное условие иначе не найдет!

# Users
urlpatterns = [
    path('login/',views.loginuser, name='loginuser'),#страница входа пользователя
    path('logout/',views.logoutuser, name='logoutuser'),#страница входа пользователя
    path('signup/',views.signup, name='signup'),#страница входа пользователя
    ]

users/models.py
from django.db import models

# Create your models here.

users/forms.py
from django import forms
from django.contrib.auth.models import User
# from django.contrib.auth.forms import UserCreationForm,UserChangeForm

class SignupForm(forms.ModelForm):
	username = forms.CharField(max_length=200, label='Логин', widget=forms.TextInput(attrs={'class': 'form-control'}))
	first_name = forms.CharField(label='Имя', widget=forms.TextInput(attrs={'class': 'form-control'}))
	last_name = forms.CharField(label='Фамилия', widget=forms.TextInput(attrs={'class': 'form-control'}))
	email = forms.EmailField(label='Почтовый ящик', widget=forms.EmailInput(attrs={'class': 'form-control'}))
	password1 = forms.CharField(label='Пароль', widget=forms.PasswordInput(attrs={'class': 'form-control'}))
	password2 = forms.CharField(label='Повторите пароль', widget=forms.PasswordInput(attrs={'class': 'form-control'}))
	class Meta:
		model = User
		fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2')
	def clean_password2(self):
		cd = self.cleaned_data
		if cd['password1'] != cd['password2']:
			raise forms.ValidationError('Пароли не совпадают!')
		return cd['password2']
	# def __init__(self, *args, **kwargs):
	# 	super(SignupForm, self).__init__(*args, **kwargs)
	# 	self.fields['password1'].widget.attrs['class'] = 'form-control'

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.forms import AuthenticationForm
from .forms import *

# Create your views here.



def logoutuser(request):
    if request.method == 'POST':
        logout(request)
        return redirect('home')


def loginuser(request):
    if request.method == 'GET':
        return render(request, 'loginuser.html', {'form': AuthenticationForm()})
    else:
        user = authenticate(request, username=request.POST['username'], password=request.POST['password'])
    if user is None:
        return render(request, 'loginuser.html', {'form': AuthenticationForm(), 'error': 'Логин и/или пароль не найдены!'})
    else:
        login(request, user)
        return redirect('home') 


def signup(request):
  # if request.method == 'POST': тут почему-то ошибка...
    user_form=SignupForm(request.POST)
    if user_form.is_valid():
      new_user = user_form.save(commit=False)
      new_user.set_password(user_form.cleaned_data['password1'])
      new_user.save()
      return render(request, 'signup.html',{'new_user':new_user})
    else:
      user_form = SignupForm()
      
    return render(request, 'signup.html', {'user_form':user_form}) #{'user_form':user_form}

users/templates/loginuser.html
{% extends 'main/base.html' %}
{% load static %}
{% block content %}

<!doctype html>
<html>
  <head>
    <meta charset="UTF-8">
    <title>Вход в систему</title>
  </head>
    <body>
        <div class="main-container">
            <div class="row justify-content-center mt-4">
                <div class="col-md-3 shadow rounded mt-5">
                    <span class="d-flex justify-content-center mt-2" style="font-size: 26px; font-weight: bold;">Войти</span>
                    {% if error %}
                        <div class="alert alert-danger mt-3 mb-5" role="alert" style="font-size: 14px;">
                            {{ error }}
                        </div>
                    {% endif %}
                    <form method="POST">
                        {% csrf_token %}
                        <div class="form-floating mb-3 mt-3">
                            <input type="text" name="username" class="form-control" id="floatingInput" placeholder="Username">
                            <label for="floatingInput" style="color: dimgray;">Логин</label>
                        </div>
                        <div class="form-floating">
                            <input type="password" name="password" class="form-control" id="floatingPassword" placeholder="Password">
                            <label for="floatingPassword" style="color: dimgray;">Пароль</label>
                        </div>
                        <div class="span mt-2">
                            {% csrf_token %}
                            <a class="nav-link d-flex justify-content-end" href ="{% url 'users:signup' %}" style="font-size: 14px;">Регистрация</a>
                            <a class="nav-link d-flex justify-content-end" href ="#" style="font-size: 12px; font-style: italic;">Забыли пароль?</a>
                        </div>
                        <div class="container d-flex justify-content-center">
                            <button type="submit" class="btn btn-primary mt-4 mb-4 shadow rounded-3" style="width: 200px;">Войти</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </body>
</html>
{% endblock %}

users/templates/logoutuser.html
<H1>Регистрация успешна!</H1>

users/templates/signup.html
{% extends 'main/base.html' %}
{% load static %}
{% block content %}
<<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Bootstrap Site</title>
</head>
<body>
	<!-- <table class="table border-0 shadow rounded" style="width: 50%; font-size: 14px;"> -->
	<div class="main-container">
		<div class="container my-2 d-flex justify-content-center mt-5">
			<form class="p-3 shadow rounded" method="post" style="width: 350px; font-size: 14px;">
				<span class="d-flex justify-content-center" style="font-size: 26px; font-weight: bold;">Зарегистрироваться</span>
					{% csrf_token %}
					{{user_form.as_p}}
					<input type="submit" value="Зарегистрироваться!" class="btn btn-primary w-100 rounded shadow mb-2 mt-2" />
			</form>
		</div>
	</div>
</body>
</html>

{% endblock %}