cart/urls.py
from django.urls import path, include
from . import views

app_name = 'cart' # обязательное условие иначе не найдет!

urlpatterns = [
    path('add-to-cart', views.add_to_cart, name='add_to_cart'), # для AJAX в main/custom.js файле
    path('delete-from-cart', views.delete_cart_item, name='delete_from_cart'), # для AJAX в main/custom.js файле
    path('update-cart', views.update_cart_item, name='update_cart_item'), # для AJAX в main/custom.js файле
    path('orders/', views.cart_list, name='cart_list'),
]

shop/urls.py
from django.contrib import admin
from django.urls import path
from main import views
from django.conf.urls.static import static
from django.urls import include
from django.conf import settings

urlpatterns = [
    # Приложение Jet-Admin (видоизмененная админка)
    path('jet/', include('jet.urls')),
    path('jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),
    path('admin/', admin.site.urls),

    path('', views.home, name='home'),

    # Приложение Cart
    path('cart/', include('cart.urls', namespace='cart')),

    # Приложение Users
    path('users/', include('users.urls', namespace='users')),
    
    path('category_list/', views.category_list, name='category_list'),
    path('brand_list/', views.brand_list, name='brand_list'),
    path('product_list/', views.product_list, name='product_list'),
    path('category_product_list/<int:cat_id>', views.category_product_list, name='category_product_list'),
    path('brand_product_list/<int:brand_id>', views.brand_product_list, name='brand_product_list'),
    path('product/<str:slug>/<int:id>', views.product_detail, name='product_detail'),
    path('search/', views.search, name='search'),
    path('filter-data/', views.filter_data, name='filter_data'),
    path('load-more-data/', views.load_more_data, name='load_more_data'),

    # Тестирование
    path('test/', views.test, name='test'),
    # path('gallery/', views.gallery, name='gallery'),
    path('slider/', views.slider, name='slider'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/models.py
from django.db import models
from django.utils.html import mark_safe

# Баннер
class Banner(models.Model):
    image = models.ImageField('Баннер', upload_to="ban_imgs/")
    alt_text = models.CharField('Текст ALT', max_length=200)
    class Meta:
        verbose_name_plural = '5. Баннеры'
    def image_tag(self):
        return mark_safe("<img src='%s' width='100' />" % (self.image.url))

# Категория
class Category(models.Model):
    title = models.CharField('Категория', max_length=100)
    image = models.ImageField('Картинка', upload_to="cat_imgs/")
    class Meta:
        verbose_name_plural = '3. Категории'
    def image_tag(self):
        return mark_safe("<img src='%s' width='50' height='50' />" % (self.image.url))
    def __str__(self):
        return self.title

# Бренд
class Brand(models.Model):
    title = models.CharField('Бренд', max_length=100)
    image = models.ImageField('Лого бренда', upload_to="brand_imgs/")
    class Meta:
        verbose_name_plural = '4. Бренды'
    def image_tag(self):
        return mark_safe("<img src='%s' width='50' height='50' />" % (self.image.url))
    def __str__(self):
        return self.title

# Цвет
class Color(models.Model):
    title = models.CharField('Цвет', max_length=100, blank=True, null=True)
    image = models.CharField('Иконка цвета', max_length=100, blank=True, null=True)
    class Meta:
        verbose_name_plural = '6. Цвета'
    def color_bg(self):
        return mark_safe('<div style="width:20px; height:20px; background-color:%s"></div>' % (self.image))
    def __str__(self):
        return self.title

# Размер
class Size(models.Model):
    title = models.CharField('Размер', max_length=100, blank=True, null=True)
    class Meta:
        verbose_name_plural = '7. Размеры'
    def __str__(self):
        return self.title

# Товар
class Product(models.Model):
    title = models.CharField('Название', max_length=250, blank=False)
    brand = models.ForeignKey(Brand, on_delete=models.CASCADE)
    sku = models.CharField('Артикул', max_length=40, blank=False, default='DEFAULT')
    video = models.CharField('Видео', max_length=300, blank=True)
    preview_desc = models.TextField('Анонс', max_length=200, null=True)
    detail_desc = models.TextField('Описание', blank=False)
    slug = models.SlugField('ЧПУ', max_length=400, db_index=True)
    specs = models.TextField('Характеристики', blank=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    active = models.BooleanField('Активность', default=True)
    in_stock = models.BooleanField('Наличие на складе', default=True)
    created = models.DateTimeField('Создан', auto_now_add=True, null=True)
    popularity = models.PositiveIntegerField('Популярность', blank=True, null=True)
    is_featured = models.BooleanField(default=False)
    class Meta:
        verbose_name_plural = '1. Товары'
    def __str__(self):
        return self.title

# Вариант товара
class ProductVariant(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    color = models.ForeignKey(Color, on_delete=models.CASCADE, blank=True, null=True)
    size = models.ForeignKey(Size, on_delete=models.CASCADE, blank=True, null=True)
    image_1 = models.ImageField('Картинка 1', default='product_imgs/no-image.jpg', upload_to="product_imgs/", blank=True, null=True) # default для того чтобы не было ощибки если провтыкаешь картинку...
    image_2 = models.ImageField('Картинка 2', upload_to="product_imgs/", blank=True, null=True)
    image_3 = models.ImageField('Картинка 3', upload_to="product_imgs/", blank=True, null=True)
    image_4 = models.ImageField('Картинка 4', upload_to="product_imgs/", blank=True, null=True)
    image_5 = models.ImageField('Картинка 5', upload_to="product_imgs/", blank=True, null=True)
    price = models.PositiveIntegerField('Розничная цена')
    old_price = models.FloatField('Старая цена', default=0.00, blank=True)
    class Meta:
        verbose_name_plural = '2. Варианты товаров'
    def __str__(self):
        return self.product.title
    def image_tag(self):
        return mark_safe("<img src='%s' width='40' height='40' />" % (self.image_1.url))

main/views.py
from django.shortcuts import render, redirect
from django.http import JsonResponse, HttpResponse
from django.template.loader import render_to_string
from .models import *
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.conf import settings
from django.views.decorators.csrf import csrf_exempt



def home(request):
    products = Product.objects.filter(is_featured=True)
    banners = Banner.objects.all()
    context = {
      'products': products,
      'banners': banners,
    }
    return render(request, 'main/index.html', context)



def category_list(request):
    cats = Category.objects.all()
    context = {
        'cats': cats,
      }
    return render(request, 'main/category_list.html', context)




def brand_list(request):
    brands = Brand.objects.all()
    context = {
        'brands': brands,
      }
    return render(request, 'main/brand_list.html', context)




def product_list(request):
    total_products = Product.objects.count()
    data = Product.objects.all()[:4]
    prices = ProductVariant.objects.all()
    context = {
        'data': data,
        'prices': prices,
        'total_products': total_products,
      }
    return render(request, 'main/product_list.html', context)




# Товары одной категории
def category_product_list(request, cat_id):
  category = Category.objects.get(id=cat_id)
  cat_products = Product.objects.filter(category=category).all()
  context = {
    'category': category,
    'cat_products': cat_products,
      }
  return render(request, 'main/category_product_list.html', context)




# Товары одного бренда
def brand_product_list(request, brand_id):
  brand = Brand.objects.get(id=brand_id)
  brand_products = Product.objects.filter(brand=brand).all()
  context = {
    'brand_products': brand_products,
      }
  return render(request, 'main/brand_product_list.html', context)




  # Детальная страница товара
def product_detail(request, slug, id):
  product = Product.objects.get(id=id)
  productvariant = ProductVariant.objects.all()

  # # experimental
  # image1 = ProductVariant.objects.filter(product=product).values('image_1')
  # image2 = ProductVariant.objects.filter(product=product).values('image_2')
  # image3 = ProductVariant.objects.filter(product=product).values('image_3')
  # image4 = ProductVariant.objects.filter(product=product).values('image_4')
  # image5 = ProductVariant.objects.filter(product=product).values('image_5')
  # print(image1,image2,image3, image4, image5)


  related_products = Product.objects.filter(category = product.category).exclude(id=id)[:4] # исключаем товар в котором находимся, показываем 4 товара
  colors = ProductVariant.objects.filter(product=product).values('color__id', 'color__title', 'color__image').distinct() # для изменения цены в зависимости от цвета и размера
  sizes = ProductVariant.objects.filter(product=product).values('size__id', 'size__title', 'price', 'color__id').distinct() # для изменения цены в зависимости от цвета и размера
  context = {
    'product': product,
    'related_products': related_products,
    'productvariant': productvariant,
    'colors': colors,
    'sizes': sizes,
  }
  return render(request, 'main/product_detail.html', context)




# Поиск
def search(request):
    q = request.GET['q']
    products = Product.objects.filter(title__icontains=q) # поиск только в заголовке товара
    context = {
      'products': products,
    }
    return render(request, 'main/search.html', context)




# Фильтр данных
def filter_data(request):
  colors = request.GET.getlist('color[]')
  categories = request.GET.getlist('category[]')
  brands = request.GET.getlist('brand[]')
  sizes = request.GET.getlist('size[]')
  minPrice = request.GET['minPrice']
  maxPrice = request.GET['maxPrice']
  allProducts = Product.objects.all().distinct()
  allProducts = allProducts.filter(productvariant__price__gte=minPrice)
  allProducts = allProducts.filter(productvariant__price__lte=maxPrice)
  if len(colors)>0:
    allProducts=allProducts.filter(productvariant__color__id__in=colors).distinct()
  if len(categories)>0:
    allProducts=allProducts.filter(category__id__in=categories).distinct()
  if len(brands)>0:
    allProducts=allProducts.filter(brand__id__in=brands).distinct()
  if len(sizes)>0:
    allProducts=allProducts.filter(productvariant__size__id__in=sizes).distinct()
  t=render_to_string('ajax/product-list.html',{'data':allProducts}) # ключ data должен быть одинаковым что и в load_more_data иначе не отобразятся изменения в product-list.html
  return JsonResponse({'data':t})



# Показать больше товаров на странице
def load_more_data(request):
	offset=int(request.GET['offset'])
	limit=int(request.GET['limit'])
	products=Product.objects.all()[offset:offset+limit]
	t=render_to_string('ajax/product-list.html',{'data':products}) # ключ data должен быть одинаковым что и в filter_data иначе не отобразятся изменения в product-list.html
	return JsonResponse({'data':t})





def test(request):
    context = {
      }
    return render(request, 'main/test.html', context)





def gallery(request):
  product = Product.objects.get(id=6)
  productvariant = ProductVariant.objects.all()
  context = {
    'product': product,
    'productvariant': productvariant,
      }
  return render(request, 'main/gallery.html', context)



def slider(request):
  context = {
      }
  return render(request, 'main/slider.html', context)








@login_required
def checkout(request):
  order_id = '123'
	
  # Process Payment
  # host = request.get_host()
  # paypal_dict = {
	# 	    'business': settings.PAYPAL_RECEIVER_EMAIL,
	# 	    'amount': '123',
	# 	    'item_name': 'OrderNo-123',
	# 	    'invoice': 'INV-123',
	# 	    'currency_code': 'USD',
	# 	    'notify_url': 'http://{}{}'.format(host,reverse('paypal-ipn')),
	# 	    'return_url': 'http://{}{}'.format(host,reverse('payment_done')),
	# 	    'cancel_return': 'http://{}{}'.format(host,reverse('payment_cancelled')),
	# 	}
  # form = PayPalPaymentsForm(initial=paypal_dict)
  # total_amount=0
  # if 'cartdata' in request.session:
  #   for p_id,item in request.session['cartdata'].items():
  #     total_amount+=int(item['qty'])*int(item['price'])
  #   total_amount = '{0:,}'.format(total_amount).replace(',', ' ')
  context = {
      # 'cart_data': request.session['cartdata'],
      # 'totalitems': len(request.session['cartdata']),
      # 'total_amount': total_amount,
      # 'form': form,
    }
  return render(request, 'cart/checkout.html', context)


@login_required
def process_payment(request):
  # order_id = '123'
  # host = request.get_host()
  # paypal_dict = {
  #   'business': settings.PAYPAL_RECEIVER_EMAIL,
  #   'amount': '123',
  #   'item_name': 'INV-123',
  #   'currency_code': 'USD',
  #   'notify_url': 'http://{}{}'.format(host, reverse('paypal-ipn')),
  #   'return_url': 'http://{}{}'.format(host, reverse('payment_done')),
  #   'cancel_return': 'http://{}{}'.format(host, reverse('payment_cancelled')),
  # }
  context = {
    # 'form': PayPalPaymentsForm(initial=paypal_dict),
  }
  return render(request, 'cart/process-payment.html', context)


@csrf_exempt
def payment_done(request):
	returnData=request.POST
	return render(request, 'cart/payment-success.html',{'data':returnData})


@csrf_exempt
def payment_canceled(request):
	return render(request, 'cart/payment-fail.html')

main/templates/main/brand_list.html
{% extends "main/base.html" %}
{% load static %} 

{% block content %}
<!DOCTYPE html>
<html lang="ru">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
    </head>
    <body>
        <div class="main-container">
                <h3 class="my-4 border-bottom pb-1">Бренды</h3>
                <div class="row row-cols-1 row-cols-lg-6 g-4">
                    {% for brand in brands %}
                    <div class="col mt-3">
                        <div class="card shadow border-0">
                            <div class="container mt-2">
                                <a href="/brand_product_list/{{brand.id}}"><img src="/media/{{brand.image}}" class="card-img-top" alt="#"></a>
                            </div>
                            <div class="card-body">
                                <h5 class="card-text" style="justify-content: center;">{{ brand.title }}</h5>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
        </div>
    </body>
</html>





{% endblock %}

main/templates/main/brand_product_list.html
{% extends "main/base.html" %}
{% load static %} 

{% block content %}
<!DOCTYPE html>
<html lang="ru">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
    </head>
    <body>
        <div class="main-container">
            <h3 class="my-4 border-bottom pb-1">Каталог</h3>
                <div class="row">
                    <div class="col-md-2">
                        {% include 'main/filters.html' %}
                    </div>

                    <div class="col-lg-10 col-md-4 product-box">
                        <div class="row g-0" id="filteredProducts">
                            {% for product in brand_products %}
                            <div class="col-md-3">
                                <div class="card h-100 shadow-none border-0">
                                    <div class="card-body">
                                        <div class="container" style="height: 75%;">
                                            <a href="/product/{{product.slug}}/{{product.id}}">
                                            {% if product.productvariant_set.first.image_1 %}
                                                <img src="/media/{{product.productvariant_set.first.image_1}}" class="card-img-top" alt="#"></a>
                                            {% else %}
                                                <img src="#" class="card-img-top" alt="#"></a>
                                            {% endif %}
                                        </div>
                                    <span class="badge mb-2 product-price-{{product.id}}" style="background-color: limegreen; font-size: 16px;">{{product.productvariant_set.first.price}}</span>
                                    <!-- <h6><span class="product-price-#">39 999 р.</span></h6> -->
                                            <h5 class="card-text" style="font-size: 12px;">{{product.detail_desc|truncatechars:70}}</h5>
                                    </div>
                                    <div class="container mb-2">
                                        <input type="hidden" min="1" max="99" value="1" class="form-control product-qty-{{product.id}}" id="productQty" style="font-size: 16px;">
                                        <input type="hidden" class="product-image-{{product.id}}" value="{{product.productvariant_set.first.image_1}}" /> <!--для корзины -->
                                        <input type="hidden" class="product-id-{{product.id}}" value="{{product.id}}" /> <!--для корзины -->
                                        <input type="hidden" class="product-title-{{product.id}}" value="{{product.title}}" /> <!--для корзины -->

                                        <button class="btn btn-sm btn-primary add-to-cart" data-index="{{product.id}}">В корзину</button>
                                        <button class="btn btn add-wishlist" data-product="#"><i class="fa fa-heart" style="color: red;"></i></button>
                                        <!-- <button class="btn btn-sm btn-danger disabled"><i class="fa fa-heart"></i></button> -->
                                        <span class="float-right ms-5" style="font-size: 12px;">4.5/5<i class="fa fa-star text-warning"></i></span>
                                    </div>
                                </div>
                            </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
        </div>

    </body>
</html>
{% endblock %}

main/templates/main/category_list.html
{% extends "main/base.html" %}
{% load static %} 

{% block content %}
<!DOCTYPE html>
<html lang="ru">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Bootstrap Site</title>
    </head>
    <body>
        <div class="main-container">
            <h3 class="my-4 border-bottom pb-1">Категории</h3>
            <div class="row row-cols-1 row-cols-lg-6 g-4">
                {% for cat in cats %}
                <div class="col mt-3">
                    <div class="card shadow border-0">
                        <div class="container mt-2">
                            <a href="/category_product_list/{{cat.id}}"><img src="/media/{{cat.image}}" class="card-img-top" alt="#"></a>
                        </div>
                        <div class="card-body">
                            <h5 class="card-text" style="justify-content: center;">{{ cat.title }}</h5>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </body>
</html>





{% endblock %}

main/templates/main/category_product_list.html
{% extends "main/base.html" %}
{% load static %} 

{% block content %}
<!DOCTYPE html>
<html lang="ru">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
    </head>
    <body>
        <div class="main-container">
            <h3 class="my-4 border-bottom pb-1">{{category.title}}</h3>
                <div class="row">
                    <div class="col-md-2">
                        {% include 'main/filters.html' %}
                    </div>

                    <div class="col-md-10">
                        <div class="row g-0" id="filteredProducts">
                            {% for product in cat_products %}
                            <div class="col-md-3">
                                <div class="card h-100 shadow-none border-0">
                                    <div class="card-body h-100">
                                        <div class="container" style="height: 75%;">
                                            <a href="/product/{{product.slug}}/{{product.id}}">
                                            {% if product.productvariant_set.first.image_1 %}
                                                <img src="/media/{{product.productvariant_set.first.image_1}}" class="card-img-top" alt="#"></a>
                                            {% else %}
                                                <img src="#" class="card-img-top" alt="#"></a>
                                            {% endif %}
                                        </div>
                                    <span class="badge mb-2 product-price-{{product.id}}" style="background-color: limegreen; font-size: 16px;">{{product.productvariant_set.first.price}}</span>
                                    <!-- <h6><span class="product-price-#">39 999 р.</span></h6> -->
                                            <h5 class="card-text" style="font-size: 12px;">{{product.detail_desc|truncatechars:70}}</h5>
                                    </div>
                                    <div class="container mb-2">
                                        <input type="hidden" min="1" max="99" value="1" class="form-control product-qty-{{product.id}}" id="productQty" style="font-size: 16px;">
                                        <input type="hidden" class="product-image-{{product.id}}" value="{{product.productvariant_set.first.image_1}}" /> <!--для корзины -->
                                        <input type="hidden" class="product-id-{{product.id}}" value="{{product.id}}" /> <!--для корзины -->
                                        <input type="hidden" class="product-title-{{product.id}}" value="{{product.title}}" /> <!--для корзины -->

                                        <button class="btn btn-sm btn-primary add-to-cart" data-index="{{product.id}}">В корзину</button>
                                        <button class="btn btn add-wishlist" data-product="#"><i class="fa fa-heart" style="color: red;"></i></button>
                                        <!-- <button class="btn btn-sm btn-danger disabled"><i class="fa fa-heart"></i></button> -->
                                        <span class="float-right ms-5" style="font-size: 12px;">4.5/5<i class="fa fa-star text-warning"></i></span>
                                    </div>
                                </div>
                            </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
        </div>

    </body>
</html>





{% endblock %}

main/templates/main/index.html
{% extends "main/base.html" %}
{% load static %}

{% block content %}
<!DOCTYPE html>
<html lang="ru">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Bootstrap Site</title>
</head>

<body>
  <div class="main-container">
    <div id="carouselExampleIndicators" class="carousel slide mt-1" data-ride="carousel">
      <ol class="carousel-indicators">
        {% for banner in banners %}
        {% if forloop.counter == 1 %}
        <li data-target="#carouselExampleIndicators" data-slide-to="{{forloop.counter}}" class="active"></li>
        {% else %}
        <li data-target="#carouselExampleIndicators" data-slide-to="{{forloop.counter}}"></li>
        {% endif %}
        {% endfor %}
      </ol>
      <div class="carousel-inner">
        {% for banner in banners %}
        {% if forloop.counter == 1 %}
        <div class="carousel-item active">
          {% else %}
          <div class="carousel-item">
          {% endif %}
          <img src="/media/{{banner.image}}" class="d-block w-100" alt="...">
        </div>
        {% endfor %}
      </div>
      <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
      </button>
      <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
      </button>
    </div>
    </div>









    <br>
    <div class="main-container">
      <div class="card-group">
        <div class="card">
          <img src="..." class="card-img-top" alt="...">
          <div class="card-body">
            <h5 class="card-title">Card title</h5>
            <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
          </div>
          <div class="card-footer">
            <small class="text-muted">Last updated 3 mins ago</small>
          </div>
        </div>
        <div class="card">
          <img src="..." class="card-img-top" alt="...">
          <div class="card-body">
            <h5 class="card-title">Card title</h5>
            <p class="card-text">This card has supporting text below as a natural lead-in to additional content.</p>
          </div>
          <div class="card-footer">
            <small class="text-muted">Last updated 3 mins ago</small>
          </div>
        </div>
        <div class="card">
          <img src="..." class="card-img-top" alt="...">
          <div class="card-body">
            <h5 class="card-title">Card title</h5>
            <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This card has even longer content than the first to show that equal height action.</p>
          </div>
          <div class="card-footer">
            <small class="text-muted">Last updated 3 mins ago</small>
          </div>
        </div>
      </div>
  </div>

      <!-- <h6 class="my-4 border-bottom pb-1">Популярное в разделе ---</h6>
      <div class="row g-0">
        {% for product in products %}
        <div class="col-md-2 mb-4">
          <div class="card shadow-none h-100 border-0">
            <div class="container images mt-2">
              <a href="/product/{{product.slug}}/{{product.id}}">
                <img class="image" src="/media/{{product.productvariant_set.first.image_1}}">
              </a>
              {% if product.productvariant_set.first.image_2 %}
              <a href="/product/{{product.slug}}/{{product.id}}">
                <img class="image" src="/media/{{product.productvariant_set.first.image_2}}">
                {% endif %}
              </a>
              {% if product.productvariant_set.first.image_3 %}
              <a href="/product/{{product.slug}}/{{product.id}}">
                <img class="image" src="/media/{{product.productvariant_set.first.image_3}}">
                {% endif %}
              </a>
              {% if product.productvariant_set.first.image_4 %}
              <a href="/product/{{product.slug}}/{{product.id}}">
                <img class="image" src="/media/{{product.productvariant_set.first.image_4}}">
                {% endif %}
              </a>
              {% if product.productvariant_set.first.image_5 %}
              <a href="/product/{{product.slug}}/{{product.id}}">
                <img class="image" src="/media/{{product.productvariant_set.first.image_5}}">
                {% endif %}
              </a>

            </div>
            <div class="card-body">
              <span class="badge mb-2 product-price-{{product.id}}"
                style="background-color: limegreen; font-size: 16px;">{{product.productvariant_set.first.price}}</span>
              <h5 class="card-text" style="font-size: 12px;">{{product.title|truncatechars:70}}</h5>
            </div>
            <div class="container mb-2">
              <input type="hidden" min="1" max="99" value="1" class="form-control product-qty-{{product.id}}"
                id="productQty" style="font-size: 16px;">
              <input type="hidden" class="product-image-{{product.id}}"
                value="{{product.productvariant_set.first.image_1}}" /> <!--для корзины -->
              <!-- <input type="hidden" class="product-id-{{product.id}}" value="{{product.id}}" /> <!--для корзины -->
              <!-- <input type="hidden" class="product-title-{{product.id}}" value="{{product.title}}" /> <!--для корзины -->
<!-- 
              <button class="btn btn-sm btn-primary add-to-cart" data-index="{{product.id}}">В корзину</button>
              <button class="btn btn add-wishlist" data-product="#"><i class="fa fa-heart"
                  style="color: red;"></i></button>
              <span class="float-right ms-2" style="font-size: 12px;">4.5/5<i class="fa fa-star text-warning"></i></span>
            </div> -->
          <!-- </div>
        </div>
        {% endfor %} -->
  </div>
      <!-- <br>
      <br>
      <br>
      <br>
      <br> -->
  <!-- </div> -->
</body>

</html>





{% endblock %}

main/templates/main/search.html
{% extends "main/base.html" %}
{% load static %} 

{% block content %}
<!DOCTYPE html>
<html lang="ru">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Bootstrap Site</title>
    </head>
    <body>

	<h6 class="my-4 border-bottom pb-1"><span class="text-muted">Результаты поиска</span> {{request.GET.q}}</h6>
	<div class="row">
    {% for product in products %}
		<div class="col-md-2 mb-4">
			<!-- <div class="card shadow"> -->
        <div class="container mt-2">
			    <a href="/product/{{product.slug}}/{{product.id}}"><img src="/media/{{product.productvariant_set.first.image_1}}" class="card-img-top" alt="#"></a>
        </div>
			  <div class="card-body">
          <span class="badge mb-2" style="background-color: limegreen; font-size: 16px;">{{product.productvariant_set.first.price}}</span>
          <!-- <h6><span class="product-price-#">39 999 р.</span></h6> -->
			    <h5 class="card-text" style="font-size: 12px;">{{product.title|truncatechars:70}}</h5>
			  </div>
        <div class="container mb-2">
          <input type="hidden" value="1" class="form-control product-qty-#" id="productQty" />
          <input type="hidden" class="product-image-#" value="#" />
          <input type="hidden" class="product-id-#" value="#" />
          <input type="hidden" class="product-title-#" value="#" />
			  	<button class="btn btn-sm btn-primary add-to-cart " data-index="#"><i class="fa fa-shopping-cart"></i></button>
			  	<button class="btn btn-sm btn-outline-danger add-wishlist" data-product="#"><i class="fa fa-heart"></i></button>
          <!-- <button class="btn btn-sm btn-danger disabled"><i class="fa fa-heart"></i></button> -->
			  	<span class="float-right ms-2" style="font-size: 12px;">4.5/5<i class="fa fa-star text-warning"></i></span>
        </div>
			<!-- </div> -->
		</div>
    {% endfor %}
	</div>





          <br>
          <br>
          <br>
          <br>
          <br>
    </body>
</html>





{% endblock %}